name: Run Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}        
    - name: setup env
      run: |
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        echo "$(dirname $GITHUB_WORKSPACE)/src"  >> $GITHUB_PATH
      shell: bash
    - name: Get dependencies
      run: go get -v -u github.com/nsone/dhammer
    - name: Switch to branch and test
      run: |
        cd $GOPATH/src/github.com/nsone/dhammer \
        && git checkout ${{github.event.pull_request.head.ref}} \
        && go test ./...
        exit $?
      shell: bash
